version: "3.9"
services:
  survey-app-database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: -c fsync=off -c full_page_writes=off -c synchronous_commit=off -c max_connections=500
    ports:
      - 10002:5432

      ## vo
